spring:
  application:
    name: backend-categoria-musica-si

  datasource:
    url: jdbc:mariadb://localhost:3307/atv2
    username: root
    password: 29200830
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect